### ISSUE TITLE
Scripts more requests!

### ISSUE THREAD

**Issue by JinxBR** [Shinobi176/EnsoulSharp#3]
Ezreal
Blitzcrank
Caitlyn

Graves
Kindred
Rengar
Sivir

Nidalee
Orianna
Lux
Annie

Brand
Vel'Koz
Viktor
Varus

Zoe

Ziggs
Camille
Corki
Jarvan
Sylas

**Comment by seskral2662** [comment]
Hi , how did you run it?

**Comment by JinxBR** [comment]
using hotfix
